
void setup()  // SADECE 1 KERE ÇALIŞIR GEREKLİ SETUPLARI YAPAR VE LOOP'A DEVREDER.
{
  pinMode(LED_BUILTIN, OUTPUT);  //LED_BUILTIN YERİNE 13'DE YAZILABİLİR 13 NUMARALI PİN ARDUİNO ÜZERİNDEKİ DAHİLİ LEDDİR.
}


void loop()  //SONSUZA KADAR ÇALIŞIR DÖNGÜ ŞEKLİNDE BİTTİKÇE BAŞA DÖNER.
{
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
}
